export const PRODUCT_CATALOG_VERSION = '2026-08-23-menu-v3';
export const INITIAL_STORE_SETTINGS = {
    storeName: 'TOKO BERKAH JAYA',
    tagline: 'Solusi Belanja Harian Hemat & Lengkap',
    address: 'Jl. Merdeka No. 45, Kebayoran Baru, Jakarta Selatan',
    phone: '0812-3456-7890',
    receiptFooter: 'Terima kasih atas kunjungan Anda!\nBarang yang sudah dibeli tidak dapat ditukar kecuali ada perjanjian.',
    taxPercent: 0,
    enableTax: false,
    currencySymbol: 'Rp',
    defaultCashierName: 'Izan (Kasir 1)',
    paperWidth: '58mm',
    businessType: 'Kedai Minuman & Dessert',
};

export const INITIAL_PRODUCTS = [
    // === KATEGORI: JUS BUAH ===
    {
        id: 'prd-mnm-01',
        name: 'Jus Mangga',
        sku: 'JUS-001',
        barcode: '8990001000011',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 50,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-01.svg'
        colorTag: '#f59e0b',
    },
    {
        id: 'prd-mnm-02',
        name: 'Jus Alpukat',
        sku: 'JUS-002',
        barcode: '8990001000028',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 40,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-02.svg'
        colorTag: '#10b981',
    },
    {
        id: 'prd-mnm-03',
        name: 'Jus Buah Naga',
        sku: 'JUS-003',
        barcode: '8990001000035',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 35,
        minStockAlert: 5,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-03.svg',
        colorTag: '#ec4899',
    },
    {
        id: 'prd-mnm-04',
        name: 'Jus Jeruk Peras',
        sku: 'JUS-004',
        barcode: '8990001000042',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 60,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-04.svg',
        colorTag: '#f97316',
    },
    {
        id: 'prd-mnm-05',
        name: 'Jus Tomat',
        sku: 'JUS-005',
        barcode: '8990001000059',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 30,
        minStockAlert: 5,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-05.svg',
        colorTag: '#ef4444',
    },
    {
        id: 'prd-mnm-06',
        name: 'Jus Semangka',
        sku: 'JUS-006',
        barcode: '8990001000066',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 45,
        minStockAlert: 8,
        unit: 'cup',
        image:'/sistem-kasir-pintar/assets/products/prd-mnm-06.svg',
        colorTag: '#f43f5e',
    },
    {
        id: 'prd-mnm-07',
        name: 'Jus Nanas',
        sku: 'JUS-007',
        barcode: '8990001000073',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 30,
        minStockAlert: 5,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-07.svg',
        colorTag: '#eab308',
    },
    {
        id: 'prd-mnm-08',
        name: 'Jus Apel',
        sku: 'JUS-008',
        barcode: '8990001000080',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 40,
        minStockAlert: 5,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-08.svg',
        colorTag: '#dc2626',
    },
    {
        id: 'prd-mnm-09',
        name: 'Jus Pear',
        sku: 'JUS-009',
        barcode: '8990001000097',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 25,
        minStockAlert: 5,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-09.svg',
        colorTag: '#a3e635',
    },
    {
        id: 'prd-mnm-10',
        name: 'Jus Melon',
        sku: 'JUS-010',
        barcode: '8990001000103',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 35,
        minStockAlert: 5,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-10.svg',
        colorTag: '#84cc16',
    },
    {
        id: 'prd-mnm-11',
        name: 'Jus Sirsak',
        sku: 'JUS-011',
        barcode: '8990001000110',
        category: 'Jus Buah',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 30,
        minStockAlert: 5,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-11.svg',
        colorTag: '#cbd5e1',
    },

    // === KATEGORI: KOPI & TEH ===
    {
        id: 'prd-mnm-12',
        name: 'Indocafe Cappucino',
        sku: 'COP-001',
        barcode: '8990002000010',
        category: 'Kopi & Teh',
        costPrice: 4300,
        sellingPrice: 7000,
        stock: 100,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-12.svg',
        colorTag: '#78350f',
    },
    {
        id: 'prd-mnm-13',
        name: 'Top Cappucino',
        sku: 'COP-002',
        barcode: '8990002000027',
        category: 'Kopi & Teh',
        costPrice: 3500,
        sellingPrice: 7000,
        stock: 100,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-13.svg',
        colorTag: '#78350f',
    },
    {
        id: 'prd-mnm-14',
        name: 'Good Day Cappucino',
        sku: 'COP-003',
        barcode: '8990002000034',
        category: 'Kopi & Teh',
        costPrice: 4200,
        sellingPrice: 7000,
        stock: 120,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-14.svg',
        colorTag: '#b45309',
    },
    {
        id: 'prd-mnm-15',
        name: 'Kopi Hitam',
        sku: 'COP-004',
        barcode: '8990002000041',
        category: 'Kopi & Teh',
        costPrice: 2500,
        sellingPrice: 5000,
        stock: 150,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-15.svg',
        colorTag: '#1e293b',
    },
    {
        id: 'prd-mnm-16',
        name: 'Kopi Susu',
        sku: 'COP-005',
        barcode: '8990002000058',
        category: 'Kopi & Teh',
        costPrice: 3000,
        sellingPrice: 7000,
        stock: 130,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-16.svg',
        colorTag: '#451a03',
    },
    {
        id: 'prd-mnm-17',
        name: 'Max Tea Tarik',
        sku: 'COP-006',
        barcode: '8990002000065',
        category: 'Kopi & Teh',
        costPrice: 3900,
        sellingPrice: 7000,
        stock: 80,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-17.svg',
        colorTag: '#d97706',
    },
    {
        id: 'prd-mnm-18',
        name: 'Milo',
        sku: 'COP-007',
        barcode: '8990002000072',
        category: 'Kopi & Teh',
        costPrice: 3700,
        sellingPrice: 7000,
        stock: 140,
        minStockAlert: 25,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-18.svg',
        colorTag: '#15803d',
    },
    {
        id: 'prd-mnm-19',
        name: 'Top Gula Aren',
        sku: 'COP-008',
        barcode: '8990002000089',
        category: 'Kopi & Teh',
        costPrice: 3700,
        sellingPrice: 7000,
        stock: 90,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-19.svg',
        colorTag: '#7c2d12',
    },
    {
        id: 'prd-mnm-20',
        name: 'Es Teh Merah',
        sku: 'COP-009',
        barcode: '8990002000096',
        category: 'Kopi & Teh',
        costPrice: 2500,
        sellingPrice: 5000,
        stock: 200,
        minStockAlert: 30,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-20.svg',
        colorTag: '#b91c1c',
    },
    {
        id: 'prd-mnm-21',
        name: 'Es Teh Hijau',
        sku: 'COP-010',
        barcode: '8990002000102',
        category: 'Kopi & Teh',
        costPrice: 2800,
        sellingPrice: 5000,
        stock: 150,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-21.svg',
        colorTag: '#16a34a',
    },

    // === KATEGORI: MINUMAN SACHET ===
    {
        id: 'prd-mnm-22',
        name: 'Extra Joss Susu',
        sku: 'SCH-001',
        barcode: '8990003000017',
        category: 'Minuman Sachet',
        costPrice: 2400,
        sellingPrice: 7000,
        stock: 85,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-22.svg',
        colorTag: '#eab308',
    },
    {
        id: 'prd-mnm-23',
        name: 'Kuku Bima Susu',
        sku: 'SCH-002',
        barcode: '8990003000024',
        category: 'Minuman Sachet',
        costPrice: 2200,
        sellingPrice: 7000,
        stock: 80,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-23.svg',
        colorTag: '#3b82f6',
    },
    {
        id: 'prd-mnm-24',
        name: 'Drink Beng-Beng',
        sku: 'SCH-003',
        barcode: '8990003000031',
        category: 'Minuman Sachet',
        costPrice: 3900,
        sellingPrice: 7000,
        stock: 95,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-24.svg',
        colorTag: '#991b1b',
    },
    {
        id: 'prd-mnm-25',
        name: 'Chocolatos Coklat',
        sku: 'SCH-004',
        barcode: '8990003000048',
        category: 'Minuman Sachet',
        costPrice: 3700,
        sellingPrice: 7000,
        stock: 110,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-25.svg',
        colorTag: '#7c2d12',
    },
    {
        id: 'prd-mnm-26',
        name: 'Chocolatos Kurma',
        sku: 'SCH-005',
        barcode: '8990003000055',
        category: 'Minuman Sachet',
        costPrice: 3700,
        sellingPrice: 7000,
        stock: 60,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-26.svg',
        colorTag: '#78350f',
    },
    {
        id: 'prd-mnm-27',
        name: 'Chocolatos Macha',
        sku: 'SCH-006',
        barcode: '8990003000062',
        category: 'Minuman Sachet',
        costPrice: 3700,
        sellingPrice: 7000,
        stock: 75,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-27.svg',
        colorTag: '#22c55e',
    },
    {
        id: 'prd-mnm-28',
        name: 'Chocolatos Creamy Coklat',
        sku: 'SCH-007',
        barcode: '8990003000079',
        category: 'Minuman Sachet',
        costPrice: 3700,
        sellingPrice: 7000,
        stock: 90,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-28.svg',
        colorTag: '#451a03',
    },
    {
        id: 'prd-mnm-29',
        name: 'Chocolatos Vanilla Latte',
        sku: 'SCH-008',
        barcode: '8990003000086',
        category: 'Minuman Sachet',
        costPrice: 3700,
        sellingPrice: 7000,
        stock: 70,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-29.svg',
        colorTag: '#e2e8f0',
    },
    {
        id: 'prd-mnm-30',
        name: 'Nutrisari Jeruk Nipis',
        sku: 'SCH-009',
        barcode: '8990003000093',
        category: 'Minuman Sachet',
        costPrice: 3100,
        sellingPrice: 5000,
        stock: 100,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-30.svg',
        colorTag: '#a3e635',
    },
    {
        id: 'prd-mnm-31',
        name: 'Nutrisari Jeruk Peras',
        sku: 'SCH-010',
        barcode: '8990003000109',
        category: 'Minuman Sachet',
        costPrice: 3100,
        sellingPrice: 5000,
        stock: 120,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-31.svg',
        colorTag: '#f97316',
    },
    {
        id: 'prd-mnm-32',
        name: 'Nutrisari Jeruk Manis',
        sku: 'SCH-011',
        barcode: '8990003000116',
        category: 'Minuman Sachet',
        costPrice: 3100,
        sellingPrice: 5000,
        stock: 100,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-32.svg',
        colorTag: '#f59e0b',
    },
    {
        id: 'prd-mnm-33',
        name: 'Nutrisari Sweet Orange',
        sku: 'SCH-012',
        barcode: '8990003000123',
        category: 'Minuman Sachet',
        costPrice: 3100,
        sellingPrice: 5000,
        stock: 110,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-33.svg',
        colorTag: '#fb923c',
    },
    {
        id: 'prd-mnm-34',
        name: 'Nutrisari Sweet Manggo',
        sku: 'SCH-013',
        barcode: '8990003000130',
        category: 'Minuman Sachet',
        costPrice: 2000,
        sellingPrice: 4000,
        stock: 90,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-34.svg',
        colorTag: '#fbbf24',
    },
    {
        id: 'prd-mnm-35',
        name: 'Nutrisari Stroberi',
        sku: 'SCH-014',
        barcode: '8990003000147',
        category: 'Minuman Sachet',
        costPrice: 3100,
        sellingPrice: 7000,
        stock: 80,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-35.svg',
        colorTag: '#f43f5e',
    },
    {
        id: 'prd-mnm-36',
        name: 'Nutrisari Nanas',
        sku: 'SCH-015',
        barcode: '8990003000154',
        category: 'Minuman Sachet',
        costPrice: 3100,
        sellingPrice: 5000,
        stock: 70,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-36.svg',
        colorTag: '#eab308',
    },
    {
        id: 'prd-mnm-37',
        name: 'Nutrisari milky orange',
        sku: 'SCH-016',
        barcode: '8990003000161',
        category: 'Minuman Sachet',
        costPrice: 3100,
        sellingPrice: 5000,
        stock: 85,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-37.svg',
        colorTag: '#fed7aa',
    },
    {
        id: 'prd-mnm-38',
        name: 'Nutrisari Anggur',
        sku: 'SCH-017',
        barcode: '8990003000178',
        category: 'Minuman Sachet',
        costPrice: 3100,
        sellingPrice: 5000,
        stock: 80,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-38.svg',
        colorTag: '#7c3aed',
    },

    // === KATEGORI: POP ICE ===
    {
        id: 'prd-mnm-39',
        name: 'Pop Ice Durian',
        sku: 'POP-001',
        barcode: '8990004000014',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 100,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-39.svg',
        colorTag: '#fde047',
    },
    {
        id: 'prd-mnm-40',
        name: 'Pop Ice Mangga',
        sku: 'POP-002',
        barcode: '8990004000021',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 100,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-40.svg',
        colorTag: '#fbbf24',
    },
    {
        id: 'prd-mnm-41',
        name: 'Pop Ice Melon',
        sku: 'POP-003',
        barcode: '8990004000038',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 90,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-41.svg',
        colorTag: '#4ade80',
    },
    {
        id: 'prd-mnm-42',
        name: 'Pop Ice Alpukat',
        sku: 'POP-004',
        barcode: '8990004000045',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 95,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-42.svg',
        colorTag: '#22c55e',
    },
    {
        id: 'prd-mnm-43',
        name: 'Pop Ice Stroberi',
        sku: 'POP-005',
        barcode: '8990004000052',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 5000,
        stock: 120,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-43.svg',
        colorTag: '#f43f5e',
    },
    {
        id: 'prd-mnm-44',
        name: 'Pop Ice Blueberry',
        sku: 'POP-006',
        barcode: '8990004000069',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 80,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-44.svg',
        colorTag: '#2563eb',
    },
    {
        id: 'prd-mnm-45',
        name: 'Pop Ice Taro',
        sku: 'POP-007',
        barcode: '8990004000076',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 110,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-45.svg',
        colorTag: '#a78bfa',
    },
    {
        id: 'prd-mnm-46',
        name: 'Pop Ice Permen karet',
        sku: 'POP-008',
        barcode: '8990004000083',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 5000,
        stock: 130,
        minStockAlert: 25,
        unit: 'cup',
        image: '/assets/products/prd-mnm-46.svg',
        colorTag: '#f472b6',
    },
    {
        id: 'prd-mnm-47',
        name: 'Pop Ice Vanilla blue',
        sku: 'POP-009',
        barcode: '8990004000090',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 100,
        minStockAlert: 20,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-47.svg',
        colorTag: '#60a5fa',
    },
    {
        id: 'prd-mnm-48',
        name: 'Pop Ice Vanilla Latte',
        sku: 'POP-010',
        barcode: '8990004000106',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 85,
        minStockAlert: 15,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-48.svg',
        colorTag: '#cbd5e1',
    },
    {
        id: 'prd-mnm-49',
        name: 'Pop Ice Coklat',
        sku: 'POP-011',
        barcode: '8990004000113',
        category: 'Pop Ice',
        costPrice: 2500,
        sellingPrice: 6000,
        stock: 150,
        minStockAlert: 30,
        unit: 'cup',
        image: '/assets/products/prd-mnm-49.svg',
        colorTag: '#7c2d12',
    },

    // === KATEGORI: DESSERT & ES TRADISIONAL ===
    {
        id: 'prd-mnm-50',
        name: 'Sup Buah',
        sku: 'DST-001',
        barcode: '8990005000011',
        category: 'Dessert & Es Tradisional',
        costPrice: 8000,
        sellingPrice: 15000,
        stock: 40,
        minStockAlert: 8,
        unit: 'porsi',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-50.svg',
        colorTag: '#ec4899',
    },
    {
        id: 'prd-mnm-51',
        name: 'Es Teler',
        sku: 'DST-002',
        barcode: '8990005000028',
        category: 'Dessert & Es Tradisional',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 35,
        minStockAlert: 8,
        unit: 'porsi',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-51.svg',
        colorTag: '#10b981',
    },
    {
        id: 'prd-mnm-52',
        name: 'Cendol Kecebong',
        sku: 'DST-003',
        barcode: '8990005000035',
        category: 'Dessert & Es Tradisional',
        costPrice: 7000,
        sellingPrice: 10000,
        stock: 45,
        minStockAlert: 10,
        unit: 'cup',
        image: '/sistem-kasir-pintar/assets/products/prd-mnm-52.svg',
        colorTag: '#047857',
    }
];

export const INITIAL_TRANSACTIONS = []
export const INITIAL_CATEGORIES = [...new Set(INITIAL_PRODUCTS.map((product) => product.category).filter(Boolean))];
